name: Beta Android

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # サブモジュールがある場合
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: List Directory
        run: ls -la android  # ディレクトリの内容を確認
      - name: List Wrapper Directory
        run: ls -la android/gradle/wrapper  # gradle-wrapper.jarが存在するか確認
      - name: Build With Gradle
        run: ./gradlew assembleDebug
        working-directory: android  # ここで正しいパスを指定
      - name: Deploy To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_DEV_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: developer
          file: android/app/build/outputs/apk/debug/app-debug.apk
